### PR TITLE
fix: update 7tv badges endpoint

### PR DESCRIPTION
**Pull request by SputNikPlop**
This is the new endpoint as the old one will be deprecated.

### CODE REVIEW

**Comment by tommyxchow** [comment]
Hello, and thanks for the PR!

I tried hitting the endpoint but got this response:
```
{
  "status_code": 410,
  "status": "Gone",
  "error": "Unknown Route",
  "error_code": 70498,
  "details": {
    "message": "The API endpoint requested does not exist"
  }
}
```

It seems like the V2 endpoints are deprecated as well, hence the error. Unfortunately, I couldn't find an equivalent endpoint in the V3 API yet.

**Comment by SputNikPlop** [comment]
Ok, lemme inquire about that then.

**Comment by tommyxchow** [comment]
Closing this PR since this particular change does not fix the bug.

**Comment by SputNikPlop** [comment]
@tommyxchow did manage to follow up on this the upstream fix is a lot more tedious than I have time for, things are also delayed on the 7tv end because of holidays

**Pull request closed without merging**
