### PR TITLE
Improve custom overlay player and add information about latency

### PR DESCRIPTION
**Pull request by Artiu**

### CODE REVIEW

**Comment by tommyxchow** [comment]
Thank you again, Artiu, for the PRs! Sadly I'm a bit busy for the next few days so I'll try to get back to your PRs later this week.

In the meantime, if possible can you add to the PRs a brief summary of the changes/implementation details? It'll help me get a better overall idea and speed up the review process (in case certain things aren't obvious like design choices or certain logic).

**Comment by Artiu** [comment]
Changes:
- added latency display,
- update video player (current custom player have problem with hidden loading spinner, so in this version I'm hiding only necessary elements instead of whole twitch overlay)

**Comment by tommyxchow** [comment]
Hey @Artiu, apologies for the delay and thanks for your patience!

I did a quick test on my device and noticed that the info portion of the Twitch overlay appears for a brief moment now. Is there a way we can hide this as well?

https://github.com/tommyxchow/frosty/assets/54859075/f49e23cb-c688-44ad-8749-fbd1d560b1c3

**Comment by Artiu** [comment]
I found different way to hide twitch overlay faster. So now overlay is not visible.

**Review by tommyxchow — APPROVED** [review]
Great work, thank you so much!

**Pull request merged**
